include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    sized_box_for_whitespace: false
    avoid_unnecessary_containers: false
    unnecessary_getters_setters: false
    prefer_typing_uninitialized_variables: false
    unnecessary_new: false
    unnecessary_this: false
