name: my_timer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^10.0.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  monarch: ^3.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/locales/

  fonts:
    - family: "Nunito Sans"
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
